export interface CountryCallingCode {
  flag: string;
  label: string;
  code: string;
}

export const COUNTRY_CALLING_CODES: readonly CountryCallingCode[] = [
  { flag: '🇦🇫', label: 'Afghanistan', code: '+93' },
  { flag: '🇦🇱', label: 'Albania', code: '+355' },
  { flag: '🇩🇿', label: 'Algeria', code: '+213' },
  { flag: '🇦🇩', label: 'Andorra', code: '+376' },
  { flag: '🇦🇴', label: 'Angola', code: '+244' },
  { flag: '🇦🇷', label: 'Argentina', code: '+54' },
  { flag: '🇦🇲', label: 'Armenia', code: '+374' },
  { flag: '🇦🇺', label: 'Australia', code: '+61' },
  { flag: '🇦🇹', label: 'Austria', code: '+43' },
  { flag: '🇦🇿', label: 'Azerbaijan', code: '+994' },
  { flag: '🇧🇸', label: 'Bahamas', code: '+1' },
  { flag: '🇧🇭', label: 'Bahrain', code: '+973' },
  { flag: '🇧🇩', label: 'Bangladesh', code: '+880' },
  { flag: '🇧🇪', label: 'Belgium', code: '+32' },
  { flag: '🇧🇿', label: 'Belize', code: '+501' },
  { flag: '🇧🇯', label: 'Benin', code: '+229' },
  { flag: '🇧🇹', label: 'Bhutan', code: '+975' },
  { flag: '🇧🇴', label: 'Bolivia', code: '+591' },
  { flag: '🇧🇦', label: 'Bosnia and Herzegovina', code: '+387' },
  { flag: '🇧🇼', label: 'Botswana', code: '+267' },
  { flag: '🇧🇷', label: 'Brazil', code: '+55' },
  { flag: '🇧🇳', label: 'Brunei', code: '+673' },
  { flag: '🇧🇬', label: 'Bulgaria', code: '+359' },
  { flag: '🇧🇫', label: 'Burkina Faso', code: '+226' },
  { flag: '🇰🇭', label: 'Cambodia', code: '+855' },
  { flag: '🇨🇲', label: 'Cameroon', code: '+237' },
  { flag: '🇨🇦', label: 'Canada', code: '+1' },
  { flag: '🇨🇱', label: 'Chile', code: '+56' },
  { flag: '🇨🇳', label: 'China', code: '+86' },
  { flag: '🇨🇴', label: 'Colombia', code: '+57' },
  { flag: '🇨🇷', label: 'Costa Rica', code: '+506' },
  { flag: '🇭🇷', label: 'Croatia', code: '+385' },
  { flag: '🇨🇾', label: 'Cyprus', code: '+357' },
  { flag: '🇨🇿', label: 'Czechia', code: '+420' },
  { flag: '🇩🇰', label: 'Denmark', code: '+45' },
  { flag: '🇩🇴', label: 'Dominican Republic', code: '+1' },
  { flag: '🇪🇨', label: 'Ecuador', code: '+593' },
  { flag: '🇪🇬', label: 'Egypt', code: '+20' },
  { flag: '🇸🇻', label: 'El Salvador', code: '+503' },
  { flag: '🇪🇪', label: 'Estonia', code: '+372' },
  { flag: '🇪🇹', label: 'Ethiopia', code: '+251' },
  { flag: '🇫🇮', label: 'Finland', code: '+358' },
  { flag: '🇫🇷', label: 'France', code: '+33' },
  { flag: '🇬🇪', label: 'Georgia', code: '+995' },
  { flag: '🇩🇪', label: 'Germany', code: '+49' },
  { flag: '🇬🇭', label: 'Ghana', code: '+233' },
  { flag: '🇬🇷', label: 'Greece', code: '+30' },
  { flag: '🇬🇹', label: 'Guatemala', code: '+502' },
  { flag: '🇭🇰', label: 'Hong Kong', code: '+852' },
  { flag: '🇭🇺', label: 'Hungary', code: '+36' },
  { flag: '🇮🇸', label: 'Iceland', code: '+354' },
  { flag: '🇮🇳', label: 'India', code: '+91' },
  { flag: '🇮🇩', label: 'Indonesia', code: '+62' },
  { flag: '🇮🇪', label: 'Ireland', code: '+353' },
  { flag: '🇮🇱', label: 'Israel', code: '+972' },
  { flag: '🇮🇹', label: 'Italy', code: '+39' },
  { flag: '🇯🇵', label: 'Japan', code: '+81' },
  { flag: '🇯🇴', label: 'Jordan', code: '+962' },
  { flag: '🇰🇿', label: 'Kazakhstan', code: '+7' },
  { flag: '🇰🇪', label: 'Kenya', code: '+254' },
  { flag: '🇰🇼', label: 'Kuwait', code: '+965' },
  { flag: '🇰🇬', label: 'Kyrgyzstan', code: '+996' },
  { flag: '🇱🇦', label: 'Laos', code: '+856' },
  { flag: '🇱🇻', label: 'Latvia', code: '+371' },
  { flag: '🇱🇧', label: 'Lebanon', code: '+961' },
  { flag: '🇱🇹', label: 'Lithuania', code: '+370' },
  { flag: '🇱🇺', label: 'Luxembourg', code: '+352' },
  { flag: '🇲🇾', label: 'Malaysia', code: '+60' },
  { flag: '🇲🇹', label: 'Malta', code: '+356' },
  { flag: '🇲🇽', label: 'Mexico', code: '+52' },
  { flag: '🇲🇩', label: 'Moldova', code: '+373' },
  { flag: '🇲🇨', label: 'Monaco', code: '+377' },
  { flag: '🇲🇳', label: 'Mongolia', code: '+976' },
  { flag: '🇲🇪', label: 'Montenegro', code: '+382' },
  { flag: '🇲🇦', label: 'Morocco', code: '+212' },
  { flag: '🇳🇱', label: 'Netherlands', code: '+31' },
  { flag: '🇳🇿', label: 'New Zealand', code: '+64' },
  { flag: '🇲🇰', label: 'North Macedonia', code: '+389' },
  { flag: '🇳🇴', label: 'Norway', code: '+47' },
  { flag: '🇴🇲', label: 'Oman', code: '+968' },
  { flag: '🇵🇰', label: 'Pakistan', code: '+92' },
  { flag: '🇵🇦', label: 'Panama', code: '+507' },
  { flag: '🇵🇾', label: 'Paraguay', code: '+595' },
  { flag: '🇵🇪', label: 'Peru', code: '+51' },
  { flag: '🇵🇭', label: 'Philippines', code: '+63' },
  { flag: '🇵🇱', label: 'Poland', code: '+48' },
  { flag: '🇵🇹', label: 'Portugal', code: '+351' },
  { flag: '🇶🇦', label: 'Qatar', code: '+974' },
  { flag: '🇷🇴', label: 'Romania', code: '+40' },
  { flag: '🇷🇸', label: 'Serbia', code: '+381' },
  { flag: '🇸🇬', label: 'Singapore', code: '+65' },
  { flag: '🇸🇰', label: 'Slovakia', code: '+421' },
  { flag: '🇸🇮', label: 'Slovenia', code: '+386' },
  { flag: '🇿🇦', label: 'South Africa', code: '+27' },
  { flag: '🇰🇷', label: 'South Korea', code: '+82' },
  { flag: '🇪🇸', label: 'Spain', code: '+34' },
  { flag: '🇱🇰', label: 'Sri Lanka', code: '+94' },
  { flag: '🇸🇪', label: 'Sweden', code: '+46' },
  { flag: '🇨🇭', label: 'Switzerland', code: '+41' },
  { flag: '🇹🇼', label: 'Taiwan', code: '+886' },
  { flag: '🇹🇯', label: 'Tajikistan', code: '+992' },
  { flag: '🇹🇭', label: 'Thailand', code: '+66' },
  { flag: '🇹🇳', label: 'Tunisia', code: '+216' },
  { flag: '🇹🇷', label: 'Turkey', code: '+90' },
  { flag: '🇹🇲', label: 'Turkmenistan', code: '+993' },
  { flag: '🇺🇦', label: 'Ukraine', code: '+380' },
  { flag: '🇦🇪', label: 'United Arab Emirates', code: '+971' },
  { flag: '🇬🇧', label: 'United Kingdom', code: '+44' },
  { flag: '🇺🇸', label: 'United States', code: '+1' },
  { flag: '🇺🇾', label: 'Uruguay', code: '+598' },
  { flag: '🇺🇿', label: 'Uzbekistan', code: '+998' },
  { flag: '🇻🇳', label: 'Vietnam', code: '+84' },
];

export const COUNTRY_CODE_OPTIONS = COUNTRY_CALLING_CODES.map((country) => ({
  label: `${country.flag} ${country.label} ${country.code}`,
  value: country.code,
}));
