// Generated by scripts/generate-tour-web-images.mjs. Originals remain available for full-size viewing.
export const TOUR_WEB_IMAGES: Readonly<Record<string, string>> = {
  '/assets/images/destinations/classic-tours-bgr.webp':
    '/assets/images/tour-web/9d728a095e2e6cf0.avif',
  '/assets/images/home-page/trips-carousel/Algeria-trip.webp':
    '/assets/images/tour-web/9fa8c652855ecbba.avif',
  '/assets/images/home-page/trips-carousel/Tour-feature-image-2.webp':
    '/assets/images/tour-web/330c342b5e356b15.avif',
  '/assets/images/home-page/trips-carousel/Tour-feature-image-1.webp':
    '/assets/images/tour-web/6c3c7fb2b543d5b9.avif',
  '/assets/images/women-tours/bulgaria-women-only-card-bgr.webp':
    '/assets/images/tour-web/a6b0538afbb9e10b.avif',
  '/assets/images/women-tours/kyrgyzstan-women-only-card-bgr.webp':
    '/assets/images/tour-web/cb63a0743b31e61d.avif',
  '/assets/images/destinations/Bulgaria/bulgaria-tour-bgr.webp':
    '/assets/images/tour-web/c5fe69b27efd7590.avif',
  '/assets/images/women-tours/Kyrgystan-women/kyrgyzstan-women-only-bgr.webp':
    '/assets/images/tour-web/84a6ace9a6cf0aee.avif',
  '/assets/images/destinations/Marocco/morocco-bgr.webp':
    '/assets/images/tour-web/866efa781a95f117.avif',
  '/assets/images/destinations/Bulgaria/gallery/Rila-Monasterry-Bulgaria-2.webp':
    '/assets/images/tour-web/8a1b2931df953f99.avif',
  '/assets/images/destinations/Bulgaria/gallery/Buzludzha-Monument-3.webp':
    '/assets/images/tour-web/510e425a0f7ec8d9.avif',
  '/assets/images/destinations/Bulgaria/gallery/Sofia-City-Tour-Bulgaria-4.webp':
    '/assets/images/tour-web/7daff3d614019f3b.avif',
};
export const TOUR_WEB_IMAGE_SRCSETS: Readonly<Record<string, string>> = {
  '/assets/images/destinations/classic-tours-bgr.webp':
    '/assets/images/tour-web/3f9edd21a59a34e7.avif 960w, /assets/images/tour-web/14dacba2195a1ff7.avif 1440w, /assets/images/tour-web/b1c5d1d34924924e.avif 1920w, /assets/images/tour-web/9d728a095e2e6cf0.avif 2560w',
};
